version: "3"
services:
  r:
    # image: atusy/atusydown:dev
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      # - "8787:8787"
      - "8787"
    environment:
      - ROOT=TRUE
      - USER=rstudio
      - PASSWORD=password
      - VIRTUAL_HOST=atusydown.localhost
    security_opt:
      - seccomp:chrome.json
    network_mode: "bridge"
